dubbo:
  application:
    name: springboot-dubbo-consumer
  registry:
    address: zookeeper://10.101.228.79:2181?backup=10.101.228.79:2182,10.101.228.79:2183
  consumer:
    timeout: 5000
server:
  port: 8005
