server:
  port: 8000

spring:
  application:
    name: springboot-dubbo-provider

dubbo:
  scan:
    base-packages: com.lemon.springbootdubboprovider.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://10.101.228.79:2181?backup=10.101.228.79:2182,10.101.228.79:2183
